language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t fwborges/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true fwborges/react-test npm test

after_sucess:
    - docker build -t fwborges/multi-client ./client
    - docker build -t fwborges/multi-nginx ./nginx
    - docker build -t fwborges/multi-server ./server
    - docker build -t fwborges/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push to docker hub
    - docker push fwborges/multi-client
    - docker push fwborges/multi-nginx
    - docker push fwborges/multi-server
    - docker push fwborges/multi-worker

